# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/User/ITMO/SoC/lab1/lab1.srcs/sources_1/bd/lab1_design/ip/lab1_design_xbar_0/lab1_design_xbar_0.xci
# IP: The module: 'lab1_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/ITMO/SoC/lab1/lab1.srcs/sources_1/bd/lab1_design/ip/lab1_design_xbar_0/lab1_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab1_design_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/User/ITMO/SoC/lab1/lab1.srcs/sources_1/bd/lab1_design/ip/lab1_design_xbar_0/lab1_design_xbar_0.xci
# IP: The module: 'lab1_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/ITMO/SoC/lab1/lab1.srcs/sources_1/bd/lab1_design/ip/lab1_design_xbar_0/lab1_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab1_design_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
