# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab1_design/lab1_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design || ORIG_REF_NAME==lab1_design} -quiet] -quiet

# IP: bd/lab1_design/ip/lab1_design_microblaze_0_0/lab1_design_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design_microblaze_0_0 || ORIG_REF_NAME==lab1_design_microblaze_0_0} -quiet] -quiet

# IP: bd/lab1_design/ip/lab1_design_axi_gpio_0_0/lab1_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design_axi_gpio_0_0 || ORIG_REF_NAME==lab1_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/lab1_design/ip/lab1_design_axi_uartlite_0_0/lab1_design_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design_axi_uartlite_0_0 || ORIG_REF_NAME==lab1_design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/lab1_design/ip/lab1_design_dlmb_v10_0/lab1_design_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design_dlmb_v10_0 || ORIG_REF_NAME==lab1_design_dlmb_v10_0} -quiet] -quiet

# IP: bd/lab1_design/ip/lab1_design_ilmb_v10_0/lab1_design_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design_ilmb_v10_0 || ORIG_REF_NAME==lab1_design_ilmb_v10_0} -quiet] -quiet

# IP: bd/lab1_design/ip/lab1_design_dlmb_bram_if_cntlr_0/lab1_design_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==lab1_design_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/lab1_design/ip/lab1_design_ilmb_bram_if_cntlr_0/lab1_design_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==lab1_design_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/lab1_design/ip/lab1_design_lmb_bram_0/lab1_design_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design_lmb_bram_0 || ORIG_REF_NAME==lab1_design_lmb_bram_0} -quiet] -quiet

# IP: bd/lab1_design/ip/lab1_design_mdm_1_0/lab1_design_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design_mdm_1_0 || ORIG_REF_NAME==lab1_design_mdm_1_0} -quiet] -quiet

# IP: bd/lab1_design/ip/lab1_design_clk_wiz_1_0/lab1_design_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design_clk_wiz_1_0 || ORIG_REF_NAME==lab1_design_clk_wiz_1_0} -quiet] -quiet

# IP: bd/lab1_design/ip/lab1_design_rst_clk_wiz_1_100M_0/lab1_design_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==lab1_design_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/lab1_design/ip/lab1_design_xbar_0/lab1_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design_xbar_0 || ORIG_REF_NAME==lab1_design_xbar_0} -quiet] -quiet

# IP: bd/lab1_design/ip/lab1_design_microblaze_0_axi_periph_0/lab1_design_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==lab1_design_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab1_design/ip/lab1_design_reset_inv_0_0/lab1_design_reset_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design_reset_inv_0_0 || ORIG_REF_NAME==lab1_design_reset_inv_0_0} -quiet] -quiet

# IP: bd/lab1_design/ip/lab1_design_getFilterOut_0_2/lab1_design_getFilterOut_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_design_getFilterOut_0_2 || ORIG_REF_NAME==lab1_design_getFilterOut_0_2} -quiet] -quiet

# XDC: bd/lab1_design/lab1_design_ooc.xdc
