# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/SoC/lab3/lab3.cache/wt [current_project]
set_property parent.project_path E:/SoC/lab3/lab3.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/admin/AppData/Roaming/Xilinx/Vivado/2019.1/xhub/board_store} [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_repo_paths e:/SoC/lab2/solution1/impl/ip [current_project]
update_ip_catalog
set_property ip_output_repo e:/SoC/lab3/lab3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/SoC/lab3/lab3.sdk/FIR_filter/Debug/FIR_filter.elf
set_property SCOPED_TO_REF lab1_design [get_files -all E:/SoC/lab3/lab3.sdk/FIR_filter/Debug/FIR_filter.elf]
set_property SCOPED_TO_CELLS microblaze_0 [get_files -all E:/SoC/lab3/lab3.sdk/FIR_filter/Debug/FIR_filter.elf]
read_verilog -library xil_defaultlib E:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/hdl/lab1_design_wrapper.v
add_files E:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/lab1_design.bd
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_microblaze_0_0/lab1_design_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_microblaze_0_0/lab1_design_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_microblaze_0_0/lab1_design_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_axi_gpio_0_0/lab1_design_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_axi_gpio_0_0/lab1_design_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_axi_gpio_0_0/lab1_design_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_axi_uartlite_0_0/lab1_design_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_axi_uartlite_0_0/lab1_design_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_axi_uartlite_0_0/lab1_design_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_dlmb_v10_0/lab1_design_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_dlmb_v10_0/lab1_design_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_ilmb_v10_0/lab1_design_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_ilmb_v10_0/lab1_design_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_dlmb_bram_if_cntlr_0/lab1_design_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_ilmb_bram_if_cntlr_0/lab1_design_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_lmb_bram_0/lab1_design_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_mdm_1_0/lab1_design_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_mdm_1_0/lab1_design_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_clk_wiz_1_0/lab1_design_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_clk_wiz_1_0/lab1_design_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_clk_wiz_1_0/lab1_design_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_rst_clk_wiz_1_100M_0/lab1_design_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_rst_clk_wiz_1_100M_0/lab1_design_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_rst_clk_wiz_1_100M_0/lab1_design_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_xbar_0/lab1_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_getFilterOut_0_2/constraints/getFilterOut_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/lab1_design_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SoC/lab3/lab3.srcs/sources_1/bd/lab1_design/ip/lab1_design_microblaze_0_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top lab1_design_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef lab1_design_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file lab1_design_wrapper_utilization_synth.rpt -pb lab1_design_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
