image: generic-c

stages:
  - check 
  - test

linter:
  stage: check
  script:
    - cd solution ; echo "Running linter" ; cat /run-checks.sh
    - /run-checks.sh

test:
  stage: test 
  script:
    - make -sj SANITIZER=all
    - make -sk test SANITIZER=all
